# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receive',
            name='rec_konlpy',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
